### PR TITLE
feat: create some basic provisioning scripts

### LINKED ISSUE #1: Create a first draft Jenkins host provisioning script

### PR DESCRIPTION
**Pull request by rpappalax**
r? @karlht @rbillings

Closes #1

### CODE REVIEW

**Comment by rbillings** [comment]
While I am unfamiliar with the ami create/monitor scripts the rest of the files match the content and format for creating an image. R+

**Comment by rpappalax** [comment]
@rbillings thanks, Rebecca!

**Comment by karlht** [comment]
This looks plausible to me.  r+

**Comment by rpappalax** [comment]
Thanks @karlht !

**Pull request merged**
